### ISSUE TITLE
Idea: Use Github discussions for discussions?

### ISSUE THREAD

**Issue by gerrymanoim** [dabeaz/blog#3]
I don't know if it would be too much or harder to manage, but I wanted to suggest using https://docs.github.com/en/discussions for the discussions. You could link to each discussion in the bottom of each post.

**Comment by dabeaz** [comment]
I don't have any experience with the discussions feature, but maybe.    I'll look into it if it's low-friction enough.

**Comment by dabeaz** [comment]
Have opened up a discussion section.   (Sorry it took so long ;-).
