### ISSUE TITLE
Lack of RSS

### ISSUE THREAD

**Issue by paulehoffman** [dabeaz/blog#6]
The / a downside of "post things on GitHub is the lack of notification for folks who want to follow your writing. Yes, we can see you tweet stuff, but if we don't immediately open a tab from the tweet, we'll forget.

**Comment by dabeaz** [comment]
There is a link to subscribe to the release RSS feed on the README.  https://github.com/dabeaz/blog/releases.atom

**Comment by paulehoffman** [comment]
Yeeps, so much for me reading the documentation. :-( Thanks!

**Comment by sstandre** [comment]
I have just noticed that there are new posts in 2023. It would be greatly appreciated if there were releases for them, to get them via RSS :)

**Comment by dabeaz** [comment]
Done.
